### ISSUE TITLE
Make all test cases in W3C trace-context test suite pass

### ISSUE THREAD

**Issue by xiang17** [open-telemetry/opentelemetry-dotnet#1219]
PR #1124 created a workflow to run W3C trace-context integration test, but there are still some failed test cases in the test suite. This issue is to track fixing of those test cases.

- [ ] Step 1: Identify and exclude the existing  failures in W3C trace context tests. In progress #1243.
- [x] Step 2: Fix each of the following testcases except for the ones failing with known external dependencies in #404. See the list of current failures in the lists below.
- [ ] Step 3: After the test cases with external dependencies got fixed, remove them from the failure list in Step 1.

## A list of current failures in Netcoreapp 2.1

Errors:
- [x] `test_tracestate_duplicated_keys`: Fixed in #1668
- [x] `test_tracestate_key_illegal_characters`: Fixed in #1668
- [x] `test_tracestate_key_illegal_vendor_format`: Fixed in #1668
- [x] `test_tracestate_key_length_limit`: Fixed in #1668
- [x] `test_tracestate_member_count_limit`: Fixed in #1668
- [x] `test_tracestate_multiple_headers_different_keys`: Fixed in #1668
- [x] `test_tracestate_value_illegal_characters`: Fixed in #1668

Failures:
- [x] `test_traceparent_trace_flags_illegal_characters`: External dependency. See issue #404 
- [x] `test_traceparent_version_0x00`: Fixed in #1668
- [x] `test_traceparent_version_0xff`: Fixed in #1668
- [x] `test_tracestate_empty_header`: Fixed in #1668

## A list of current failures in Netcoreapp 3.1

Errors:
- [x] `test_tracestate_duplicated_keys`: Fixed in #1668
- [x] `test_tracestate_key_illegal_characters`: Fixed in #1668
- [x] `test_tracestate_key_illegal_vendor_format`: Fixed in #1668
- [x] `test_tracestate_key_length_limit`: Fixed in #1668
- [x] `test_tracestate_member_count_limit`: Fixed in #1668
- [x] `test_tracestate_multiple_headers_different_keys`: Fixed in #1668
- [x] `test_tracestate_value_illegal_characters`: Fixed in #1668

Failures:
- [x] `test_traceparent_parent_id_all_zero`: External dependency. See issue #404
- [x] `test_traceparent_parent_id_illegal_characters`: External dependency. See issue #404
- [x] `test_traceparent_trace_flags_illegal_characters`: External dependency. See issue #404
- [x] `test_traceparent_version_0x00`: Fixed in #1668
- [x] `test_traceparent_version_0xff`: Fixed in #1668
- [x] `test_tracestate_empty_header`: Fixed in #1668

## A list of current failures in Netcoreapp 5.0

Failures:
- [x] `test_traceparent_parent_id_all_zero`: External dependency. See issue #404
- [x] `test_traceparent_parent_id_illegal_characters`: External dependency. See issue #404
- [x] `test_traceparent_trace_flags_illegal_characters`: External dependency. See issue #404

# Appendix

Output of current test run:

## Netcoreapp 2.1

```
Test Name:	OpenTelemetry.Instrumentation.W3cTraceContext.Tests.W3CTraceContextTests.W3CTraceContextTestSuite
Test Outcome:	Passed
Result StandardOutput:	
2021-01-07T21:40:55.3453427Z: Starting application at: http://localhost:5000
result:test_multiple_requests_with_illegal_traceparent (__main__.AdvancedTest)
harness sends an invalid traceparent and asks vendor service to callback multiple times ... ok
test_multiple_requests_with_valid_traceparent (__main__.AdvancedTest)
harness sends a valid traceparent and asks vendor service to callback multiple times ... ok
test_multiple_requests_without_traceparent (__main__.AdvancedTest)
harness asks vendor service to callback multiple times ... ok
test_both_traceparent_and_tracestate_missing (__main__.TraceContextTest)
harness sends a request without traceparent or tracestate ... ok
test_traceparent_duplicated (__main__.TraceContextTest)
harness sends a request with two traceparent headers ... ok
test_traceparent_header_name (__main__.TraceContextTest)
harness sends an invalid traceparent using wrong names ... ok
test_traceparent_header_name_valid_casing (__main__.TraceContextTest)
harness sends a valid traceparent using different combination of casing ... ok
test_traceparent_included_tracestate_missing (__main__.TraceContextTest)
harness sends a request with traceparent but without tracestate ... ok
test_traceparent_ows_handling (__main__.TraceContextTest)
harness sends an valid traceparent with heading and trailing OWS ... ok
test_traceparent_parent_id_all_zero (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id = 0000000000000000 ... ok
test_traceparent_parent_id_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in parent_id ... ok
test_traceparent_parent_id_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id more than 16 HEXDIG ... ok
test_traceparent_parent_id_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id less than 16 HEXDIG ... ok
test_traceparent_trace_flags_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in trace_flags ... FAIL
test_traceparent_trace_flags_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_flags more than 2 HEXDIG ... ok
test_traceparent_trace_flags_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_flags less than 2 HEXDIG ... ok
test_traceparent_trace_id_all_zero (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_id = 00000000000000000000000000000000 ... ok
test_traceparent_trace_id_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in trace_id ... ok
test_traceparent_trace_id_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_id more than 32 HEXDIG ... ok
test_traceparent_trace_id_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_id less than 32 HEXDIG ... ok
test_traceparent_version_0x00 (__main__.TraceContextTest)
harness sends an invalid traceparent with extra trailing characters ... ok
test_traceparent_version_0xcc (__main__.TraceContextTest)
harness sends an valid traceparent with future version 204 (0xcc) ... ok
test_traceparent_version_0xff (__main__.TraceContextTest)
harness sends an invalid traceparent with version 255 (0xff) ... ok
test_traceparent_version_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in version ... ok
test_traceparent_version_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with version more than 2 HEXDIG ... ok
test_traceparent_version_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with version less than 2 HEXDIG ... ok
test_tracestate_all_allowed_characters (__main__.TraceContextTest)
harness sends a request with a valid tracestate header with all legal characters ... ok
test_tracestate_duplicated_keys (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with duplicated keys ... ok
test_tracestate_empty_header (__main__.TraceContextTest)
harness sends a request with empty tracestate header ... ok
test_tracestate_header_name (__main__.TraceContextTest)
harness sends an invalid tracestate using wrong names ... ok
test_tracestate_header_name_valid_casing (__main__.TraceContextTest)
harness sends a valid tracestate using different combination of casing ... ok
test_tracestate_included_traceparent_included (__main__.TraceContextTest)
harness sends a request with both tracestate and traceparent ... ok
test_tracestate_included_traceparent_missing (__main__.TraceContextTest)
harness sends a request with tracestate but without traceparent ... ok
test_tracestate_key_illegal_characters (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with illegal key ... ok
test_tracestate_key_illegal_vendor_format (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with illegal vendor format ... ok
test_tracestate_key_length_limit (__main__.TraceContextTest)
harness sends tracestate header with a key of 256 and 257 characters ... ok
test_tracestate_member_count_limit (__main__.TraceContextTest)
harness sends a request with a valid tracestate header with 32 list members ... ok
test_tracestate_multiple_headers_different_keys (__main__.TraceContextTest)
harness sends a request with multiple tracestate headers, each contains different set of keys ... ok
test_tracestate_ows_handling (__main__.TraceContextTest)
harness sends a request with a valid tracestate header with OWS ... ok
test_tracestate_value_illegal_characters (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with illegal value format ... ok

======================================================================
FAIL: test_traceparent_trace_flags_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in trace_flags
----------------------------------------------------------------------
Traceback (most recent call last):
  File "trace-context/test/test.py", line 366, in test_traceparent_trace_flags_illegal_characters
    self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: '12345678901234567890123456789012' == '12345678901234567890123456789012'

----------------------------------------------------------------------
Ran 40 tests in 2.152s

FAILED (failures=1)

2021-01-07T21:40:59.4407181Z: Disposing WebHost starting.....
2021-01-07T21:40:59.4674592Z: Disposing WebHost completed.
```

## Netcoreapp 3.1

```
Test Name:	OpenTelemetry.Instrumentation.W3cTraceContext.Tests.W3CTraceContextTests.W3CTraceContextTestSuite
Test Outcome:	Passed
Result StandardOutput:	
2021-01-07T21:41:02.1168886Z: Starting application at: http://localhost:5000
result:test_multiple_requests_with_illegal_traceparent (__main__.AdvancedTest)
harness sends an invalid traceparent and asks vendor service to callback multiple times ... ok
test_multiple_requests_with_valid_traceparent (__main__.AdvancedTest)
harness sends a valid traceparent and asks vendor service to callback multiple times ... ok
test_multiple_requests_without_traceparent (__main__.AdvancedTest)
harness asks vendor service to callback multiple times ... ok
test_both_traceparent_and_tracestate_missing (__main__.TraceContextTest)
harness sends a request without traceparent or tracestate ... ok
test_traceparent_duplicated (__main__.TraceContextTest)
harness sends a request with two traceparent headers ... ok
test_traceparent_header_name (__main__.TraceContextTest)
harness sends an invalid traceparent using wrong names ... ok
test_traceparent_header_name_valid_casing (__main__.TraceContextTest)
harness sends a valid traceparent using different combination of casing ... ok
test_traceparent_included_tracestate_missing (__main__.TraceContextTest)
harness sends a request with traceparent but without tracestate ... ok
test_traceparent_ows_handling (__main__.TraceContextTest)
harness sends an valid traceparent with heading and trailing OWS ... ok
test_traceparent_parent_id_all_zero (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id = 0000000000000000 ... FAIL
test_traceparent_parent_id_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in parent_id ... FAIL
test_traceparent_parent_id_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id more than 16 HEXDIG ... ok
test_traceparent_parent_id_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id less than 16 HEXDIG ... ok
test_traceparent_trace_flags_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in trace_flags ... FAIL
test_traceparent_trace_flags_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_flags more than 2 HEXDIG ... ok
test_traceparent_trace_flags_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_flags less than 2 HEXDIG ... ok
test_traceparent_trace_id_all_zero (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_id = 00000000000000000000000000000000 ... ok
test_traceparent_trace_id_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in trace_id ... ok
test_traceparent_trace_id_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_id more than 32 HEXDIG ... ok
test_traceparent_trace_id_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_id less than 32 HEXDIG ... ok
test_traceparent_version_0x00 (__main__.TraceContextTest)
harness sends an invalid traceparent with extra trailing characters ... ok
test_traceparent_version_0xcc (__main__.TraceContextTest)
harness sends an valid traceparent with future version 204 (0xcc) ... ok
test_traceparent_version_0xff (__main__.TraceContextTest)
harness sends an invalid traceparent with version 255 (0xff) ... ok
test_traceparent_version_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in version ... ok
test_traceparent_version_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with version more than 2 HEXDIG ... ok
test_traceparent_version_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with version less than 2 HEXDIG ... ok
test_tracestate_all_allowed_characters (__main__.TraceContextTest)
harness sends a request with a valid tracestate header with all legal characters ... ok
test_tracestate_duplicated_keys (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with duplicated keys ... ok
test_tracestate_empty_header (__main__.TraceContextTest)
harness sends a request with empty tracestate header ... ok
test_tracestate_header_name (__main__.TraceContextTest)
harness sends an invalid tracestate using wrong names ... ok
test_tracestate_header_name_valid_casing (__main__.TraceContextTest)
harness sends a valid tracestate using different combination of casing ... ok
test_tracestate_included_traceparent_included (__main__.TraceContextTest)
harness sends a request with both tracestate and traceparent ... ok
test_tracestate_included_traceparent_missing (__main__.TraceContextTest)
harness sends a request with tracestate but without traceparent ... ok
test_tracestate_key_illegal_characters (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with illegal key ... ok
test_tracestate_key_illegal_vendor_format (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with illegal vendor format ... ok
test_tracestate_key_length_limit (__main__.TraceContextTest)
harness sends tracestate header with a key of 256 and 257 characters ... ok
test_tracestate_member_count_limit (__main__.TraceContextTest)
harness sends a request with a valid tracestate header with 32 list members ... ok
test_tracestate_multiple_headers_different_keys (__main__.TraceContextTest)
harness sends a request with multiple tracestate headers, each contains different set of keys ... ok
test_tracestate_ows_handling (__main__.TraceContextTest)
harness sends a request with a valid tracestate header with OWS ... ok
test_tracestate_value_illegal_characters (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with illegal value format ... ok

======================================================================
FAIL: test_traceparent_parent_id_all_zero (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id = 0000000000000000
----------------------------------------------------------------------
Traceback (most recent call last):
  File "trace-context/test/test.py", line 321, in test_traceparent_parent_id_all_zero
    self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: '12345678901234567890123456789012' == '12345678901234567890123456789012'

======================================================================
FAIL: test_traceparent_parent_id_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in parent_id
----------------------------------------------------------------------
Traceback (most recent call last):
  File "trace-context/test/test.py", line 331, in test_traceparent_parent_id_illegal_characters
    self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: '12345678901234567890123456789012' == '12345678901234567890123456789012'

======================================================================
FAIL: test_traceparent_trace_flags_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in trace_flags
----------------------------------------------------------------------
Traceback (most recent call last):
  File "trace-context/test/test.py", line 366, in test_traceparent_trace_flags_illegal_characters
    self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: '12345678901234567890123456789012' == '12345678901234567890123456789012'

----------------------------------------------------------------------
Ran 40 tests in 2.297s

FAILED (failures=3)

2021-01-07T21:41:06.1181685Z: Disposing WebHost starting.....
2021-01-07T21:41:06.1461009Z: Disposing WebHost completed.
```

## Netcoreapp 5.0

```
Test Name:	OpenTelemetry.Instrumentation.W3cTraceContext.Tests.W3CTraceContextTests.W3CTraceContextTestSuite
Test Outcome:	Passed
Result StandardOutput:	
2021-01-07T21:40:46.8960601Z: Starting application at: http://localhost:5000
result:test_multiple_requests_with_illegal_traceparent (__main__.AdvancedTest)
harness sends an invalid traceparent and asks vendor service to callback multiple times ... ok
test_multiple_requests_with_valid_traceparent (__main__.AdvancedTest)
harness sends a valid traceparent and asks vendor service to callback multiple times ... ok
test_multiple_requests_without_traceparent (__main__.AdvancedTest)
harness asks vendor service to callback multiple times ... ok
test_both_traceparent_and_tracestate_missing (__main__.TraceContextTest)
harness sends a request without traceparent or tracestate ... ok
test_traceparent_duplicated (__main__.TraceContextTest)
harness sends a request with two traceparent headers ... ok
test_traceparent_header_name (__main__.TraceContextTest)
harness sends an invalid traceparent using wrong names ... ok
test_traceparent_header_name_valid_casing (__main__.TraceContextTest)
harness sends a valid traceparent using different combination of casing ... ok
test_traceparent_included_tracestate_missing (__main__.TraceContextTest)
harness sends a request with traceparent but without tracestate ... ok
test_traceparent_ows_handling (__main__.TraceContextTest)
harness sends an valid traceparent with heading and trailing OWS ... ok
test_traceparent_parent_id_all_zero (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id = 0000000000000000 ... FAIL
test_traceparent_parent_id_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in parent_id ... FAIL
test_traceparent_parent_id_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id more than 16 HEXDIG ... ok
test_traceparent_parent_id_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id less than 16 HEXDIG ... ok
test_traceparent_trace_flags_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in trace_flags ... FAIL
test_traceparent_trace_flags_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_flags more than 2 HEXDIG ... ok
test_traceparent_trace_flags_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_flags less than 2 HEXDIG ... ok
test_traceparent_trace_id_all_zero (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_id = 00000000000000000000000000000000 ... ok
test_traceparent_trace_id_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in trace_id ... ok
test_traceparent_trace_id_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_id more than 32 HEXDIG ... ok
test_traceparent_trace_id_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with trace_id less than 32 HEXDIG ... ok
test_traceparent_version_0x00 (__main__.TraceContextTest)
harness sends an invalid traceparent with extra trailing characters ... ok
test_traceparent_version_0xcc (__main__.TraceContextTest)
harness sends an valid traceparent with future version 204 (0xcc) ... ok
test_traceparent_version_0xff (__main__.TraceContextTest)
harness sends an invalid traceparent with version 255 (0xff) ... ok
test_traceparent_version_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in version ... ok
test_traceparent_version_too_long (__main__.TraceContextTest)
harness sends an invalid traceparent with version more than 2 HEXDIG ... ok
test_traceparent_version_too_short (__main__.TraceContextTest)
harness sends an invalid traceparent with version less than 2 HEXDIG ... ok
test_tracestate_all_allowed_characters (__main__.TraceContextTest)
harness sends a request with a valid tracestate header with all legal characters ... ok
test_tracestate_duplicated_keys (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with duplicated keys ... ok
test_tracestate_empty_header (__main__.TraceContextTest)
harness sends a request with empty tracestate header ... ok
test_tracestate_header_name (__main__.TraceContextTest)
harness sends an invalid tracestate using wrong names ... ok
test_tracestate_header_name_valid_casing (__main__.TraceContextTest)
harness sends a valid tracestate using different combination of casing ... ok
test_tracestate_included_traceparent_included (__main__.TraceContextTest)
harness sends a request with both tracestate and traceparent ... ok
test_tracestate_included_traceparent_missing (__main__.TraceContextTest)
harness sends a request with tracestate but without traceparent ... ok
test_tracestate_key_illegal_characters (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with illegal key ... ok
test_tracestate_key_illegal_vendor_format (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with illegal vendor format ... ok
test_tracestate_key_length_limit (__main__.TraceContextTest)
harness sends tracestate header with a key of 256 and 257 characters ... ok
test_tracestate_member_count_limit (__main__.TraceContextTest)
harness sends a request with a valid tracestate header with 32 list members ... ok
test_tracestate_multiple_headers_different_keys (__main__.TraceContextTest)
harness sends a request with multiple tracestate headers, each contains different set of keys ... ok
test_tracestate_ows_handling (__main__.TraceContextTest)
harness sends a request with a valid tracestate header with OWS ... ok
test_tracestate_value_illegal_characters (__main__.TraceContextTest)
harness sends a request with an invalid tracestate header with illegal value format ... ok

======================================================================
FAIL: test_traceparent_parent_id_all_zero (__main__.TraceContextTest)
harness sends an invalid traceparent with parent_id = 0000000000000000
----------------------------------------------------------------------
Traceback (most recent call last):
  File "trace-context/test/test.py", line 321, in test_traceparent_parent_id_all_zero
    self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: '12345678901234567890123456789012' == '12345678901234567890123456789012'

======================================================================
FAIL: test_traceparent_parent_id_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in parent_id
----------------------------------------------------------------------
Traceback (most recent call last):
  File "trace-context/test/test.py", line 331, in test_traceparent_parent_id_illegal_characters
    self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: '12345678901234567890123456789012' == '12345678901234567890123456789012'

======================================================================
FAIL: test_traceparent_trace_flags_illegal_characters (__main__.TraceContextTest)
harness sends an invalid traceparent with illegal characters in trace_flags
----------------------------------------------------------------------
Traceback (most recent call last):
  File "trace-context/test/test.py", line 366, in test_traceparent_trace_flags_illegal_characters
    self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
AssertionError: '12345678901234567890123456789012' == '12345678901234567890123456789012'

----------------------------------------------------------------------
Ran 40 tests in 1.757s

FAILED (failures=3)

2021-01-07T21:40:52.6482366Z: Disposing WebHost starting.....
2021-01-07T21:40:52.6822527Z: Disposing WebHost completed.
```

**Comment by martinjt** [comment]
There are no longer tests failing here.
