### ISSUE TITLE
Improve instrumentation documentation

### ISSUE THREAD

**Issue by alanwest** [open-telemetry/opentelemetry-dotnet#1233]
Improve instrumentation documentation and make the format consistent across all the supported libraries.

@cijothomas Is this the list of items you had in mind for this effort? If so, I can pick some of these up.

- [x] [OpenTelemetry.Instrumentation.AspNet](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.AspNet) #1205
- [x] [OpenTelemetry.Instrumentation.AspNetCore](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.AspNetCore) #1228
- [x] [OpenTelemetry.Instrumentation.GrpcNetClient](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.GrpcNetClient) #1213
- [x] [OpenTelemetry.Instrumentation.Http](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.Http)
- [x] [OpenTelemetry.Instrumentation.SqlClient](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.SqlClient)
- [x] [OpenTelemetry.Instrumentation.StackExchangeRedis](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.StackExchangeRedis)

**Comment by cijothomas** [comment]
For SQL (https://github.com/open-telemetry/opentelemetry-dotnet/issues/1222), can you add some text to clarify that full SQL Query is supported in only following scenarios:
.NET Core - System.Data.SQlCient or Microsoft.Data.SqlClient 
.NET Framework - Microsoft.Data.SqlClient
.NET Framework + System.Data.SqlClient - no ability to get full SQL text.
