### ISSUE TITLE
Donate https://github.com/aspnet/Microsoft.AspNet.TelemetryCorrelation to OpenTelemetry

### ISSUE THREAD

**Issue by reyang** [open-telemetry/opentelemetry-dotnet#2222]
This has been discussed during the [OpenTelemetry .NET SIG Meeting at 08/03/2021 4PM PT](https://docs.google.com/document/d/1yjjD6aBcLxlRazYrawukDgrhZMObwHARJbB9glWdHj8/edit#heading=h.k27gy3m31psv).

Here are the steps that we will be following:

* [x] Fork a “aspnet-telemetrycorrelation” branch from main
* [x] Just copy the code, with no change (#2223)
* [x] Make minimum change to clean up Microsoft specific stuff (comments, types, etc.) (#2224, #2225)
* [x] Fix the styling/sanity check/project/solution/build (#2226, #2229, #2231, #2235, #2244)
* [x] Integrate it with the instrumentation library, major change could happen at this stage. We should also pick a better namespace and package name (#2238, #2240)
* [x] Update test cases (#2240)
* [x] Update changelog (#2242)
* [x] Merge the “aspnet-telemetrycorrelation” branch back to main, keep individual commit history rather than squash the commits (#2233)
* [x] Delete the “aspnet-telemetrycorrelation” branch
* [x] Do a test release (most likely we'll just catch the 1.2.0 alpha release train)

FYI @open-telemetry/dotnet-maintainers
