### ISSUE TITLE
Support exemplars in Metrics

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#2527]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exemplar

## First stable release (1.9.0)

* SDK default behavior will be `AlwaysOff`. The spec says the default `SHOULD` be `TraceBased`. We decided to deviate from this due to performance concerns when `Exemplar`s are enabled: #5545

* Expose APIs covered by the [Exemplar diagnostic](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/diagnostics/experimental-apis/OTEL1002.md): 

  This will allow users to enable `Exemplar`s either `AlwaysOn` or `TraceBased` for all metrics.

* Add an environment variable for turning on `Exemplar`s specifically for histograms:

   We feel `Exemplar`s are most useful when combined with histograms. The current spec design is all-or-nothing. Due to the performance concerns, we have decided to expose an experiment mechanism for enabling `Exemplar`s for histograms only. The plan is for this to be a temporary thing while we work to improve the spec to allow for this scenario via a stable API.

* Tasks:

   * [X] Remove ExemplarFilter API: #5333
   * [X] Give ExemplarReservoir + View API its own diagnostic: #5334, #5558
   * [X] Add an experimental envvar for enabling exemplars for histograms: #5611
   * [X] Remove experimental api decorations & update OTEL1002 diagnostic: #5607
   * [X] Add docs which show how to use the view api portion: #5624
   * [X] Add example which shows how to implement a custom reservoir: #5624

## Future release

* Propose spec changes to make it easier to enable `Exemplar`s for specific metrics: https://github.com/open-telemetry/opentelemetry-specification/pull/4014

* Propose spec changes to make it easier to enable `Exemplar`s for specific instrument types: TODO

* Expose APIs covered by the [ExemplarReservoir diagnostic](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/diagnostics/experimental-apis/OTEL1004.md):

   We felt the use case for building custom `ExemplarReservoir`s is unclear. We want to gather feedback before exposing something.

**Comment by cijothomas** [comment]
Have reviewed this in detail, and concluded the changes are non-trivial, and will not be part of 1.4.0 (Nov 2022) release. We expect to add beta support for this, shortly after 1.4.0 has shipped, with the goal of making it stable by 1.5.0 (no ETA for stable yet, but 3-4 months after 1.4.0)

**Comment by cijothomas** [comment]
Update:
1.5.0-alpha.1 added basic exemplar support. See https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/customizing-the-sdk#exemplars

E2E Example/Demo - https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/exemplars

Basic implementation only, more coming in then next few weeks.

**Comment by CodeBlanch** [comment]
I just updated the description for the plan @cijothomas and I have worked out for 1.9.0 and releasing `Exemplar`s stable. We decided to stay close to what the spec has defined.

Users who want to turn on `Exemplar`s can do so using the spec-defined `SetExemplarFilter` mechanism. If enabled, the SDK will use all the spec-defined default `ExemplarReservoir`s.

We feel the cost for enabling `Exemplar`s for all metrics is too high and they are most useful for histograms. We want to enable the scenario of turning on `Exemplar`s just for histograms. What we are going to do is introduce an experimental envvar for this. See the details below for why we decided to go this route. The key point is it will work in stable builds and doesn't require an API which would require a prerelease build.

We have decided NOT to expose `ExemplarReservoir` or the configuration via the View API in the first release. This will only be available in prerelease builds. We want to gather feedback first on the use cases to make sure what is being exposed will meet the needs of users. It also seems likely the default reservoirs may change so we were hesitant to expose those initially.

<details>
<summary>Details</summary>

The main design we considered was this:

* Set SDK `ExemplarFilterType` default to: `TraceBased` (spec-compliant)
* Set the default `ExemplarReservoir` to `NoopExemplarReservoir` or `SimpleFixedSizeExemplarReservoir(0)` (deviates from the spec-defined defaults)
* Allow users to use the View API to set `ExemplarReservoir` to `SimpleFixedSizeExemplarReservoir`, `AlignedHistogramBucketExemplarReservoir`, or something custom (spec-compliant).

This is a pretty big deviation from the spec. It forces users to use the View API to enable `Exemplar`s individually for any metric where they are needed. It also requires a lot of API to be exposed publicly. There is also a concern that if users were to enable `Exemplar`s via something like `AlignedHistogramBucketExemplarReservoir` and then the spec comes up with a better default algorithm, users would have to update their code to take advantage of that in future releases. `ExemplarReservoir` is a more advanced API. For users who want to selectively enable/disable `Exemplar`s forcing that into the `ExemplarReservoir` seemed heavy-handed. We felt it better to work through the spec to enable such scenarios in well-defined APIs.

We feel the spec API is good at enabling or disabling `Exemplar`s for everything. The only core use case we felt was not represented is enabling `Exemplar`s for just histograms. There isn't a good way to do this via the spec. Our current thinking is this API would be useful:

```csharp
meterProviderBuilder.SetExemplarFilter(InstrumentType.Histogram, ExemplarFilterType.TraceBased)
```

But we would need to expose that experimentally which would only be available in pre-release builds. We're going to go with an experimental envvar for histograms to get close in a way that will work in stable builds.
</details>

**Comment by prajon84** [comment]
@CodeBlanch : Does it mean that exemplars can be turned on by `SetExemplarFilter(ExemplarFilterType.TraceBased)`, but only for histogram metrics with release `1.9.0` ?

**Comment by cijothomas** [comment]
> @CodeBlanch : Does it mean that exemplars can be turned on by `SetExemplarFilter(ExemplarFilterType.TraceBased)`, but only for histogram metrics with release `1.9.0` ?

`SetExemplarFilter(ExemplarFilterType.TraceBased)` will enable for all instruments, not just histograms.

**Comment by prajon84** [comment]
Well, Do you have any example with counter metrics? I do not see any relevant example

**Comment by prajon84** [comment]
@cijothomas thank you but that gives only counter value and timestamp as exemplar. If I want something like `traceID` as exemplar, how could I do that I was expecting  `ExemplartFilterType.TraceBased` to do that but no luck.

**Comment by cijothomas** [comment]
> @cijothomas thank you but that gives only counter value and timestamp as exemplar. If I want something like `traceID` as exemplar, how could I do that I was expecting `ExemplartFilterType.TraceBased` to do that but no luck.

Have you enabled Tracing, which is pre-req for seeing TraceId in exemplars. Please open a new issue, with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) showing the problem being faced.

**Comment by prajon84** [comment]
ok. I misunderstood initially, I enabled tracing:
- Add Source in Tracing
- Add Meter in Metrics
- Had to updated metrics within using block of activity.StartActivity....
- ANd, I noticed that I can see exemplars with `TraceId` and `SpanId` - if I use `COnsoleExporter`

- However, if I use OtelExporter or PrometheusExporter, I cannot see those exemplars.
🤔
