### ISSUE TITLE
Epic: Implementing Metrics

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-dotnet#316]
Implementing metrics falls into 4 buckets. API, instrumentation adapters, data pipeline, export. Breakdown is below.

**For all the items - before starting, please create an issue and link it from this epic.**

## API implementation

- [X] Basic API. Done by @cijothomas 
- [ ] Handles and other optimizations
- [ ] API documentation
- [ ] API usability review

## API Usage (instrumentation adapters)

- [ ] Expose metrics from instrumentation Adapter.
  - [ ] #68 
  - [ ] Other? SQL, GRPC?
- [ ] Performance counters collection
  - [ ] Windows Performance Counters
  - [ ] Event Counters in .NET Core
  - [ ] Others

## Data pipeline

- [ ] Ensure specs are in place
- [ ] Implement Metric Processor
- [ ] Implement metrics aggregations

## Export

- [ ] Metrics Data Model. Define all the aggregates that SDK allows to configure out of the box.
- [ ] Prometheus exporter. See also https://github.com/open-telemetry/opentelemetry-dotnet/labels/area%3A%20Exporter.Prometheus
- [ ] OpenTelemetry Collector exporter
