### ISSUE TITLE
Support Exponential Histogram

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/opentelemetry-dotnet#4189]
Issue to track the overall support of Exponential Histogram.

TODOs:

- [x] Add support to the SDK
- [x] Examine the imprecision of MapToIndex (#4509) with regards to the following TODOs in the following code
    * https://github.com/open-telemetry/opentelemetry-dotnet/blob/1510b76634f4fdfbf79cd73e4b71aaf474e40a46/src/OpenTelemetry/Metrics/Base2ExponentialBucketHistogram.cs#L153-L166
- [x] OTLP exporter support (#4337)
- [x] In-Memory exporter support (#4303)
- [x] Console exporter support (#4344 (in-progress))
- [x] Update docs demonstrating how to configure exponential histograms
- [x] Update example applications to support configuring exponential histograms
- [x] Benchmarks
- [x] Run Stress tests to rule out memory leak issues
- [x] Public API review
