### ISSUE TITLE
[epic] Replace TagTransformer with a higher perf solution

### ISSUE THREAD

**Issue by CodeBlanch** [open-telemetry/opentelemetry-dotnet#5475]
Today we use the shared [TagTransformer](https://github.com/open-telemetry/opentelemetry-dotnet/blob/21aeaa70c06093134b6747779458d2ebd5bdb453/src/Shared/TagTransformer.cs) in OtlpExporter, ZipkinExporter, & ConsoleExporter.

There are some issues with its design:

* It has to return things. In the case of OtlpExporter, it returns classes generated from the protos (KeyValue, AnyValue, ArrayValue, etc.). In the case of ZipkinExporter and ConsoleExporter, it returns strings. These things all must be allocated and garbage collected. In the ZipkinExporter case, the json sent to Zipkin misrepresents bool/double/long tag values as strings.

* It leaves array-handling code up to each implementation. OtlpExporter has a [switch](https://github.com/open-telemetry/opentelemetry-dotnet/blob/21aeaa70c06093134b6747779458d2ebd5bdb453/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpTagTransformer.cs#L82-L97) which must match the logic of the base class. ZipkinExporter and ConsoleExporter use [TagTransformerJsonHelper](https://github.com/open-telemetry/opentelemetry-dotnet/blob/21aeaa70c06093134b6747779458d2ebd5bdb453/src/Shared/TagTransformerJsonHelper.cs) which must match the base class and be annotated correctly for AoT compilation.

This epic is to track replacing `TagTransformer` with something which has the following design goals:

* It should be possible to write directly onto something (instead of returning the thing to write). This is how we achieve high-performance and eliminate allocations. In the case of ZipkinExporter, we can write directly to the outgoing stream. OtlpExporter will still write onto the proto objects. But follow-up projects (probably #5450) should be able to utilize this design to write directly onto a stream or buffer (sort of how PrometheusExporter works today). ConsoleExporter will continue to build strings for now as it is primarily a test tool. But this work could be utilized to support emitting JSON or YAML to the console efficiently and potentially make the performance suitable for production usage.

* All of the array handling should be encapsulated into the base class. Implementations shouldn't need to worry about the supported types only writing out the normalized string/long/double/bool values.

* ZipkinExporter should respect bool/double/long tag values.

Tasks:

* [X] Add new tag writer implementation: #5476
* [X] Update OtlpExporter to use the new implementation: #5585
* [X] Update ZipkinExporter to use the new implementation: #5590
* [X] Update ConsoleExporter to use the new implementation: #5596
* [X] Remove existing implementation: #5602
